### ISSUE TITLE
Rename notebook to avoid use of "historical"

### ISSUE THREAD

**Issue by wjchulme** [opensafely/tpp-database-history#64]
The notebook title should probably now just be "OpenSAFELY-TPP database coverage", i.e., without "historical" in the title (or maybe a better title altogether if there's an appetite for a discussion about that)

It also covers just the most recent 30 days or so, which for "historical" isn't really the right vibe. It hopefully will also signal to users who've used the platform for a long time that this is the new place to go for all coverage info. At least for those who were used to it being split across two notebooks and missed the memo about the changes.

**Comment by iaindillingham** [comment]
Reasonable 🙂

On thing, though: that set of charts is for the last 30 days _of event activity_ - we should clarify this means _for which there is event activity_. Sometimes, the 30-day period can be historical.

For example, when I ran the report on 2023-05-16 we had ICNARC data from 2020-12-20 to 2021-01-20. The ICNARC chart, then, shows this 30-day period and not the 30-day period from 2023-04-16 to 2023-05-16.

**Comment by iaindillingham** [comment]
> On thing, though: that set of charts is for the last 30 days of event activity - we should clarify this means for which there is event activity. Sometimes, the 30-day period can be historical.

See #60
